PLATFORM_SELECTORS = {
    "qidian": {
        "item": [
            ".book-img-text li",
            ".rank-view-list .book-img-text li",
            ".rank-body li",
            ".book-list li",
            "li[data-rid]",
            "div[class*='book-img-text'] li",
        ],
        "title": [
            ".book-mid-info h2 a::text",
            "h2 a::text",
            ".book-info h3 a::text",
            ".book-name a::text",
            "a.name::text",
            "a::attr(title)",
        ],
        "author": [
            ".author .name::text",
            ".author a::text",
            ".writer::text",
        ],
        "category": [
            ".author a:nth-child(4)::text",
            ".author a.go-sub-type::text",
            ".type::text",
        ],
        "tags": [
            ".tag span::text",
            ".tag a::text",
            ".state-box span::text",
        ],
        "summary": [
            ".intro::text",
            ".book-mid-info .intro::text",
            "p.intro::text",
        ],
        "rank": [
            "::attr(data-rid)",
            ".rank-tag::text",
            ".rank::text",
            ".num::text",
        ],
        "heat": [
            ".total span::text",
            ".update span::text",
            ".score::text",
        ],
        "next_page": [
            ".lbf-pagination-next::attr(href)",
            ".lbf-pagination-next a::attr(href)",
            ".pagination .next::attr(href)",
            ".pagination-next::attr(href)",
            "a.next::attr(href)",
            "a[rel='next']::attr(href)",
        ],
    },
    "zongheng": {
        "item": [
            ".rank-modules-works--main-item",
            ".rank_d_list .rank_d_book",
            ".rank-list .rank-item",
            ".rank-list li",
            ".rank-body li",
            ".book-list li",
            ".rank-item",
            "div[class*='rank'] li",
        ],
        "title": [
            ".rank-modules-works--main-item-title::text",
            ".rank-modules-works--main-item-title::attr(title)",
            ".bookname a::text",
            ".book-name a::text",
            ".rank_d_b_name a::text",
            ".rank-book-name a::text",
            "h2 a::text",
            "h3 a::text",
            "a::attr(title)",
        ],
        "author": [
            ".rank-modules-works--main-item-author a:first-child::text",
            ".rank-modules-works--main-item-author a:nth-of-type(1)::text",
            ".author a::text",
            ".bookilnk a::text",
            ".writer::text",
        ],
        "category": [
            ".rank-modules-works--main-item-author a:nth-of-type(2)::text",
            ".cate a::text",
            ".book-category::text",
            ".type a::text",
        ],
        "tags": [
            ".keyword span::text",
            ".tags a::text",
            ".book-label span::text",
        ],
        "summary": [
            ".rank-modules-works--main-item-desc::attr(title)",
            ".rank-modules-works--main-item-desc::text",
            ".intro::text",
            ".book-dec::text",
            ".desc::text",
        ],
        "rank": [
            ".rank::text",
            ".rank_num::text",
            ".num::text",
        ],
        "heat": [
            ".rank-content--btn-text::text",
            ".btn-top-text span::text",
            ".tickets::text",
            ".book-meta span::text",
            ".score::text",
        ],
        "next_page": [
            ".pagination .next::attr(href)",
            ".page-next::attr(href)",
            ".next::attr(href)",
            "a.next::attr(href)",
            "a[rel='next']::attr(href)",
        ],
    },
}
