"""Tests for safe_search.uid_utils — generate_uid and validate_uid."""

import sys
from unittest.mock import MagicMock

# Pre-register modules that engine.py depends on but aren't relevant to
# these tests. This avoids ImportError during safe_search package init.
sys.modules["sentiment_critic"] = MagicMock()
sys.modules["sentiment_critic.critic"] = MagicMock()

from safe_search.uid_utils import generate_uid, validate_uid


# ---------------------------------------------------------------------------
# generate_uid
# ---------------------------------------------------------------------------

class TestGenerateUid:
    """Coverage: deterministic output, empty inputs, whitespace stripping."""

    def test_deterministic_same_inputs(self) -> None:
        """Same (platform_id, novel_title) always yields the same UID."""
        uid1 = generate_uid("qidian:12345678", "诡秘之主")
        uid2 = generate_uid("qidian:12345678", "诡秘之主")
        assert uid1 == uid2
        assert len(uid1) == 64

    def test_different_inputs_different_uids(self) -> None:
        """Different platform_id or title produce different UIDs."""
        uid_a = generate_uid("plat:A", "Title One")
        uid_b = generate_uid("plat:B", "Title One")
        uid_c = generate_uid("plat:A", "Title Two")
        assert uid_a != uid_b
        assert uid_a != uid_c

    def test_empty_platform_id(self) -> None:
        """An empty platform_id still produces a deterministic 64-char hash."""
        uid = generate_uid("", "Some Title")
        assert len(uid) == 64
        assert isinstance(uid, str)
        # Verify it's deterministic
        assert uid == generate_uid("", "Some Title")

    def test_empty_title(self) -> None:
        """An empty novel_title still produces a deterministic hash."""
        uid = generate_uid("plat:1", "")
        assert len(uid) == 64
        assert uid == generate_uid("plat:1", "")

    def test_both_empty(self) -> None:
        """Both empty strings produce the hash of '|'."""
        uid = generate_uid("", "")
        assert len(uid) == 64
        assert uid == generate_uid("", "")

    def test_strips_title_whitespace(self) -> None:
        """Leading/trailing whitespace on title is stripped before hashing."""
        uid_clean = generate_uid("plat:1", "Hello")
        uid_spacy = generate_uid("plat:1", "  Hello  ")
        assert uid_clean == uid_spacy

    def test_strips_title_whitespace_only(self) -> None:
        """A title that is only whitespace is treated as empty after strip."""
        uid_ws = generate_uid("plat:1", "   ")
        uid_empty = generate_uid("plat:1", "")
        assert uid_ws == uid_empty

    def test_output_is_lowercase_hex(self) -> None:
        """The UID must be a lowercase hex string (64 chars)."""
        uid = generate_uid("test", "data")
        assert uid == uid.lower()
        int(uid, 16)  # raises ValueError if not valid hex

    def test_output_length(self) -> None:
        """SHA256 produces exactly 64 hex characters."""
        uid = generate_uid("any", "thing")
        assert len(uid) == 64


# ---------------------------------------------------------------------------
# validate_uid
# ---------------------------------------------------------------------------

class TestValidateUid:
    """Coverage: valid format, wrong length, non-hex chars, empty string."""

    def test_accepts_valid_64_char_hex(self) -> None:
        """A real UID generated by generate_uid must be valid."""
        uid = generate_uid("qidian:123", "诡秘之主")
        assert validate_uid(uid) is True

    def test_accepts_manual_valid_hex(self) -> None:
        """64 lowercase hex digits are accepted."""
        uid = "a" * 64
        assert validate_uid(uid) is True

    def test_accepts_mixed_digits(self) -> None:
        """All hex characters (0-9, a-f) work."""
        uid = "0123456789abcdef" * 4  # exactly 64 chars
        assert len(uid) == 64
        assert validate_uid(uid) is True

    def test_rejects_too_short(self) -> None:
        """Fewer than 64 characters is invalid."""
        assert validate_uid("a" * 63) is False

    def test_rejects_too_long(self) -> None:
        """More than 64 characters is invalid."""
        assert validate_uid("a" * 65) is False

    def test_rejects_non_hex_chars(self) -> None:
        """Characters outside 0-9, a-f (and A-F) are invalid."""
        # 'g' is not valid hex
        assert validate_uid("g" + "a" * 63) is False
        # 'z' is not valid hex
        assert validate_uid("a" * 63 + "z") is False
        # uppercase G
        assert validate_uid("a" * 63 + "G") is False

    def test_rejects_empty_string(self) -> None:
        """Empty string has length 0, not 64."""
        assert validate_uid("") is False

    def test_accepts_uppercase_hex(self) -> None:
        """int(..., 16) accepts uppercase, so validate_uid accepts it too."""
        assert validate_uid("A" * 64) is True

    def test_rejects_none(self) -> None:
        """None is not a string; validate_uid raises."""
        import pytest

        with pytest.raises((AttributeError, TypeError)):
            validate_uid(None)  # type: ignore[arg-type]
